# Generated by Django 4.2.4 on 2023-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Список')),
                ('description', models.TextField(max_length=1000, verbose_name='Названия')),
            ],
        ),
    ]
